<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

namespace App\Grpc\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OrderPackage.OrderItem</code>
 */
class OrderItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>int32 qty = 2;</code>
     */
    protected $qty = 0;
    /**
     * Generated from protobuf field <code>float unit_price = 3;</code>
     */
    protected $unit_price = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type int $qty
     *     @type float $unit_price
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Order::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 qty = 2;</code>
     * @return int
     */
    public function getQty()
    {
        return $this->qty;
    }

    /**
     * Generated from protobuf field <code>int32 qty = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setQty($var)
    {
        GPBUtil::checkInt32($var);
        $this->qty = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float unit_price = 3;</code>
     * @return float
     */
    public function getUnitPrice()
    {
        return $this->unit_price;
    }

    /**
     * Generated from protobuf field <code>float unit_price = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setUnitPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->unit_price = $var;

        return $this;
    }

}

