<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

namespace App\Grpc\Message;

use UnexpectedValueException;

/**
 * Protobuf type <code>OrderPackage.OrderStatus</code>
 */
class OrderStatus
{
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_UNSPECIFIED = 0;</code>
     */
    const ORDER_STATUS_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_PENDING = 1;</code>
     */
    const ORDER_STATUS_PENDING = 1;
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_PAID = 2;</code>
     */
    const ORDER_STATUS_PAID = 2;
    /**
     * Generated from protobuf enum <code>ORDER_STATUS_CANCELLED = 3;</code>
     */
    const ORDER_STATUS_CANCELLED = 3;

    private static $valueToName = [
        self::ORDER_STATUS_UNSPECIFIED => 'ORDER_STATUS_UNSPECIFIED',
        self::ORDER_STATUS_PENDING => 'ORDER_STATUS_PENDING',
        self::ORDER_STATUS_PAID => 'ORDER_STATUS_PAID',
        self::ORDER_STATUS_CANCELLED => 'ORDER_STATUS_CANCELLED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

